//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IMainService")]
    public interface IMainService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/ComputeNumber", ReplyAction="http://tempuri.org/IMainService/ComputeNumberResponse")]
        string ComputeNumber(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/ComputeNumber", ReplyAction="http://tempuri.org/IMainService/ComputeNumberResponse")]
        System.Threading.Tasks.Task<string> ComputeNumberAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetNumbers", ReplyAction="http://tempuri.org/IMainService/GetNumbersResponse")]
        System.Collections.Generic.Dictionary<string, string> GetNumbers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetNumbers", ReplyAction="http://tempuri.org/IMainService/GetNumbersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetNumbersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainServiceChannel : WebApplication4.ServiceReference2.IMainService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainServiceClient : System.ServiceModel.ClientBase<WebApplication4.ServiceReference2.IMainService>, WebApplication4.ServiceReference2.IMainService {
        
        public MainServiceClient() {
        }
        
        public MainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ComputeNumber(string input) {
            return base.Channel.ComputeNumber(input);
        }
        
        public System.Threading.Tasks.Task<string> ComputeNumberAsync(string input) {
            return base.Channel.ComputeNumberAsync(input);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetNumbers() {
            return base.Channel.GetNumbers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetNumbersAsync() {
            return base.Channel.GetNumbersAsync();
        }
    }
}
